# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 04:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180204_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='dia1',
            field=models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO')], default='LUN', max_length=3),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='dia2',
            field=models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO')], default='LUN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='dia3',
            field=models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO')], default='LUN', max_length=3, null=True),
        ),
    ]
